### ISSUE TITLE
change the color but it not working

### ISSUE THREAD

**Issue by m061i6** [s780609/archer-loader#1]
change the color but it not working
```
loader.show("#466995", 1.5, "Loading...");
```
I change the color code to "#466995" ,  but it still set the default color.

**Comment by s780609** [comment]
Dear m061i6
The version `1.1.3` can not change display text's background color, it will always be dark green.
But the `v1.1.4` can change by first parameter (color code), now the circle color and the text's background color will remain the same.
Please update to `v1.1.4` if you want this behavior.
